### ISSUE TITLE
Error when ran with ASkyBlock

### ISSUE THREAD

**Issue by Carisus** [atesin/villageinfo#1] opened 2016-08-06 02:24 UTC
I am not really sure if this is from your plugin. Actually, I am pretty sure it isn't, but was hoping you could help me track it down.

http://pastebin.com/eVKSqCwf

I ran this on a test server and had no problems. It only errors like this if [this](https://github.com/tastybento/askyblock) plugin is installed.  I think ASkyBlock is taking over the villages so your plugin isn't seeing them. But I can't find it in their [code](https://github.com/tastybento/askyblock/blob/e827c8b145eb96b93620ed66e2ce22f5ab28282e/src/com/wasteofplastic/askyblock/listeners/IslandGuard.java#L548). I could be completely wrong. I am not a Java developer, just have been working with Java for too long. 

Any help would be great.

**Comment by atesin** [comment] 2016-08-07 06:04
put an eye on craftbukkit and villageinfo versions and to be compatible each other

if you mean villageinfo alone does not throw exceptions, but together with skyblock throes an npe ... i think maybe the issue is related with world names ... maybe at some point skyblock changes world names so villageinfo doesn't find it (get null). so it tries to do world operations over a null object and throws the npe

can you confirm that?

**Comment by Carisus** [comment] 2016-08-07 13:31
My Spigot and VI versions are compatable. Same exact jars are used for the testing. VI works with Spigot by itself but when I add ASkyBlock it errors.

 The second suggestion would actually explain the problem. ASkyBlock creates its own world, and I doubt it actually registers it with bukkit. I have had problems finding the world with other plugins.  Thank you so much for your help, it would have taken me forever to figure that out. I will consider this closed.

**Comment by atesin** [comment] 2016-08-08 04:40
you're welcome

do some test and tell me how it result to update project
- open villageinfo jar with some archiver and extract plugin.yml (backup first)
- edit this line in plugin.yml... add plugin name to the list as registered in bukkit:

softdepend: [(...), 'askyblock']
- this way villageinfo should wait until askyblock loads
- add yml back to the jar and test it

**Comment by Carisus** [comment] 2016-08-08 08:07
I did as you asked and received the same error. But I was looking at ASkyBlocks GitHub today and found [this bit of code](https://github.com/tastybento/askyblock/blob/master/src/com/wasteofplastic/askyblock/ASkyBlock.java#L143). What he is doing here is creating a custom world for the islands. He is using his own code, unless Muliverse-Core is loaded, then he will use it. 

I use Multiworld, not Multiverse-Core. So I decided to try it with Multiverse-Core. At first I got the same error. Then I removed all the files in ASkyBlock except for it's config and restarted. Your plugin worked giving me the correct information on the village with no errors.

Just to be sure I removed ASkyBlock as a softdepend and tried again. It still worked, no error. I can't think of anything you can do to get around this issue. It isn't your problem. You were the first person to go to because villageinfo is the one throwing the error.

Let me know if you want me to do any more testing.

**Comment by atesin** [comment] 2016-08-08 15:29
i agree is not my problem, but until is unfair i found easier and faster my plugin to handle it instead tell askyblock staff to fix it ... actually i am someway glad the problem persists so i have not to fix it and confirms askyblock people should do

thanks for your contributions ... i will close the issue and document it

**Closed as completed by atesin** 2016-08-08 15:29 UTC
